In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [3]:
tf.__version__

'2.18.0'

Predicting the electrical energy output of a Combined Cycle Power Plant using ANN Model Regression

In [4]:
df = pd.read_excel('Folds5x2_pp.xlsx')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
print(X)
print('--'*30)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
------------------------------------------------------------
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [7]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
[473.93 467.87 431.97 ... 459.01 462.72 428.12]
[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [8]:
ann_regression = tf.keras.models.Sequential()

# Sequential() adalah kelas yang digunakan membuat ANN secara sequence. Berasal dari models module, dimana merupakan module dari kelas
# dan kereas merupakan submodule dari tensorflow

In [9]:
# input layer
ann_regression.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))
# dense class, connection betweeen input layer and hideen layer
# units specified how many neurons we want
# activation, specified what type of activation function that we want to use

In [10]:
# second hidden layer
ann_regression.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

In [11]:
# final layer -> output layer
ann_regression.add(tf.keras.layers.Dense(units=1 ))

# since we are dealing with a continuous dataset, the recomendded function activation is sigmoid
# if we deal with classification with two output, use sigmoid, if over 2 use softmax (classfification), if there over than 2 and it is continuous
# (especially here regression) then we do not need a function activation

In [12]:
# compiling the ANN

ann_regression.compile(optimizer= 'adam' , loss= 'mean_squared_error')

In [13]:
# fitting teh training set to the ann model

ann_regression.fit(X_train, y_train, batch_size= 32 , epochs= 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 241625.7188
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 206291.9688
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 205481.7031
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 205421.5312
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 204379.3281
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 109222.5469
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 133.5605
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 127.1385
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 113.1417
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 108.9110
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99.3359
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 94.9894
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 87.3234
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 77.4975
E

In [14]:
y_pred = ann_regression.predict(X_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [15]:
np.set_printoptions(precision= 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[432.26 431.23]
 [463.17 460.01]
 [466.64 461.14]
 ...
 [473.9  473.26]
 [440.75 438.  ]
 [459.94 463.28]]


On the left is the predicted value and on the right is the actual value


We can see that the predicted value is very close to the actual value
meaning the model has worked well.